<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CS2103/T Textbook - Error Handling: Exceptions</title>
    <link rel="stylesheet" href="..\..\markbind\css\bootstrap.min.css">
    <link rel="stylesheet" href="..\..\markbind\css\github.min.css">
</head>
<body>
<div id="app" class="container-fluid">
    <link rel="stylesheet" href="/se-book/css/textbook.css">
<div class="website-content">
  <p><span class="dimmed"><strong>Error Handling ‚û°Ô∏è</strong></span></p>
  <h2 id="exceptions">Exceptions</h2>
  <div id="main">
    <div>
      <div>
        <h4 id="what-one">What <img style="height: 1em;width: 1em;margin: 0 .05em 0 .1em;vertical-align: -0.1em;" src="https://assets-cdn.github.com/images/icons/emoji/unicode/0031-20e3.png"></h4>
      </div>
      <tip-box type="success">
        <div>
          <p>üèÜ Can explain exceptions <img style="height: 1em;width: 1em;margin: 0 .05em 0 .1em;vertical-align: -0.1em;" src="https://assets-cdn.github.com/images/icons/emoji/unicode/0031-20e3.png"></p>
        </div>
      </tip-box>
      <panel type="seamless" header=" %%- - - - - - - - - -%%">
        <div>
          <div>
            <p>Exceptions are used to deal with ‚Äòunusual‚Äô but not entirely unexpected situations that the program might encounter at run time.</p>
            <tip-box type="primary">
              <div>
                <p><strong>Exception</strong>:</p>
                <blockquote>
                  <p>An <em>exception</em> is an event, which occurs during the execution of a program, that disrupts the normal flow of the program's instructions.</p>
                  <p>‚Äì- Java Tutorial (Oracle Inc.)</p>
                </blockquote>
              </div>
            </tip-box>
            <tip-box>
              <p>Examples:</p>
              <ul>
                <li>A network connection encounters a timeout due to a slow server.</li>
                <li>The code tries to read a file from the hard disk but the file is corrupted and cannot be read.</li>
              </ul>
            </tip-box>
            <p>Exceptions are not program bugs. Rather, they are unusual situations that need to be recovered from, if possible.</p>
          </div>
        </div>
      </panel>
    </div>
    <div>
      <div>
        <h4 id="how-two">How <img style="height: 1em;width: 1em;margin: 0 .05em 0 .1em;vertical-align: -0.1em;" src="https://assets-cdn.github.com/images/icons/emoji/unicode/0032-20e3.png"></h4>
      </div>
      <tip-box type="success">
        <div>
          <p>üèÜ Can do exception handling in code <img style="height: 1em;width: 1em;margin: 0 .05em 0 .1em;vertical-align: -0.1em;" src="https://assets-cdn.github.com/images/icons/emoji/unicode/0032-20e3.png"></p>
        </div>
      </tip-box>
      <panel type="seamless" header=" %%- - - - - - - - - -%%">
        <div>
          <div>
            <p>However, the code segment that encountered the unusual situation might not know how to recover from it. That is why most languages allow a method to encapsulate the unusual situation in an Exception object and ‚Äòthrow‚Äô that object so that another
              piece of code can ‚Äòcatch‚Äô it and deal with it. Usually, an exception thrown by a method is caught by the caller method. If the called method does not know how to deal with the exception it caught, it will throw the Exception object to its
              own caller. If none of the callers is prepared to deal with the exception, the exceptions can propagate through the method call stack until it is received by the main method and thrown to the runtime, thus halting the system. In the Java
              code given below, <code>processArray</code> can potentially throw an <code>InvalidInputException</code>. Because of that, <code>processInput</code> method invokes <code>processArray</code> method inside a <code>try{ }</code> block and has
              a <code>catch{ }</code> block to specify what to do if the exception is actually thrown.</p>
            <tip-box>
              <p>Example:</p><img src="/se-book/errorHandling/exceptions/how/images/processInput.png" height="320">
              <p></p>
            </tip-box>
            <p>Advantages of exception handling in this way:</p>
            <ul>
              <li>The ability to propagate error information through the call stack.</li>
              <li>The separation of code that deals with ‚Äòunusual‚Äô situations from the code that does the ‚Äòusual‚Äô work.</li>
            </ul>
          </div>
        </div>
      </panel>
    </div>
    <div>
      <div>
        <h4 id="when-three">When <img style="height: 1em;width: 1em;margin: 0 .05em 0 .1em;vertical-align: -0.1em;" src="https://assets-cdn.github.com/images/icons/emoji/unicode/0033-20e3.png"></h4>
      </div>
      <tip-box type="success">
        <div>
          <p>üèÜ Can avoid using exceptions to control normal workflow <img style="height: 1em;width: 1em;margin: 0 .05em 0 .1em;vertical-align: -0.1em;" src="https://assets-cdn.github.com/images/icons/emoji/unicode/0033-20e3.png"></p>
        </div>
      </tip-box>
      <panel type="seamless" header=" %%- - - - - - - - - -%%">
        <div>
          <div>
            <p>{to add: do not use exceptions for normal workflow}</p>
          </div>
        </div>
      </panel>
    </div>
  </div>
</div>
</div>
</body>
<script src="..\..\markbind\js\vue.min.js"></script>
<script src="..\..\markbind\js\vue-strap.min.js"></script>
<script src="..\..\markbind\js\setup.js"></script>
</html>
